repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
    -   id: check-yaml
    -   id: check-json
    -   id: check-toml
    -   id: check-added-large-files
    -   id: fix-byte-order-marker
        name: Fix UTF-8 byte order marker
    -   id: check-case-conflict
    -   id: check-merge-conflict
        name: Check for files that contain merge conflict strings.
    -   id: check-symlinks
        name: Checks for symlinks which do not point to anything
    -   id: detect-private-key
        name: Detects the presence of private keys


-   repo: https://github.com/pre-commit/mirrors-isort
    rev: 'v5.7.0'
    hooks:
    -   id: isort
        name: Fix files with isort

#-   repo: local
#    hooks:
#    -   id: isort
#        name: Fix files with isort
#        entry: isort
#        language: system
#        types: [python]

-   repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
    -   id: black
        name: Fix files with black
        language_version: python3

#-   repo: local
#    hooks:
#    -   id: black
#        name: Fix files with black
#        entry: black
#        language: system
#        types: [python]


-   repo: local
    hooks:
    -   id: pylint
        name: Check code with pylint
        entry: pylint
        language: system
        types: [python]

-   repo: local
    hooks:
    -   id: mypy
        name: Check python files with mypy
        entry: mypy  --ignore-missing-imports
        language: system
        types: [python]

-   repo: https://github.com/Lucas-C/pre-commit-hooks-safety
    rev: v1.1.3
    hooks:
    -   id: python-safety-dependencies-check
        name: Check package vulnerabilities with safety

-   repo: https://github.com/PyCQA/bandit
    rev: 1.7.0
    hooks:
    -   id: bandit
        name: Check code vulnerabilities with bandit
        args: ['-iii', '-ll']

-   repo: local
    hooks:
    -   id: pytest-check
        name: Test with pytest
        entry: pytest
        language: system
        pass_filenames: false
        always_run: true



