# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
    -   id: check-yaml
    -   id: check-json
    -   id: check-toml
    -   id: check-added-large-files
    -   id: fix-byte-order-marker
    -   id: check-case-conflict

-   repo: https://github.com/psf/black
    rev: 20.8b1 # Replace by any tag/version: https://github.com/psf/black/tags
    hooks:
    -   id: black
        language_version: python3 # Should be a command that runs python3.6+
        args:
            - --check

-   repo: https://github.com/Lucas-C/pre-commit-hooks-safety
    rev: v1.1.3
    hooks:
    -   id: python-safety-dependencies-check

- repo: https://github.com/PyCQA/bandit
  rev: 1.6.2
  hooks:
    - id: bandit
      args: ['-iii', '-ll']

#-   repo: https://github.com/pycqa/pylint
#    rev: pylint-2.5.3
#    hooks:
#    -   id: pylint

#-   repo: https://github.com/pre-commit/mirrors-mypy
#    rev: ''  # Use the sha / tag you want to point at
#    hooks:
#    -   id: mypy
#        additional_dependencies: [tokenize-rt==3.2.0]
#        args:
#            - ./mk/
#            - ./test/


-   repo: local
    hooks:
    -   id: pytest-check
        name: pytest-check
        entry: pytest
        language: system
        pass_filenames: false
        always_run: true
        stages:
        -   push

    -   id: pylint
        name: pylint
        entry: pylint
        language: system
        types: [python]

#    -   id: mypy
#        name: mypy
#        entry: mypy .
#        language: python
#        types: [python]


