fail_fast: true
repos:

  # Fast checks  ::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::

  - repo: https://github.com/commitizen-tools/commitizen
    rev: v2.20.0
    hooks:
      - id: commitizen
        stages: [ commit-msg ]

  # Fast checks  ::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-case-conflict
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-symlinks
      - id: destroyed-symlinks

  # Format files  :::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: fix-byte-order-marker
      - id: trailing-whitespace
      - id: end-of-file-fixer

  - repo: https://github.com/pre-commit/mirrors-isort
    rev: 'v5.9.3'
    hooks:
      - id: isort
        name: Format python files with isort

  - repo: https://github.com/psf/black
    rev: 21.9b0
    hooks:
      - id: black
        name: Format python files with black
        language_version: python3


  # Verify files  :::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-yaml
      - id: check-json
      - id: check-toml
      - id: detect-private-key

  #  - repo: local
  #    hooks:
  #      - id: pylint
  #        entry: poetry run pylint
  #        language: system
  #        types: [ python ]
  #        require_serial: true
  #        name: Check code with pylint

  - repo: local
    hooks:
      - id: mypy
        name: Check python files with mypy
        entry: mypy  --ignore-missing-imports
        language: system
        types: [ python ]

  # Test ::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::

  - repo: local
    hooks:
      - id: pytest
        name: "Test with pytest"
        language: system
        entry: poetry run pytest
        types: [ python ]
        pass_filenames: false

  # Check file and package security vulnerabilities :::::::::::::::::::::::::::::::::::::::::::::::::

  - repo: local
    hooks:
      - id: safety
        name: "Check package vulnerabilities with safety"
        language: system
        entry: poetry run safety check
        pass_filenames: false

  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.0
    hooks:
      - id: bandit
        name: "Check code vulnerabilities with bandit"
        args: [ '-iii', '-ll' ]
