[tool.poetry]
name = "creat"
version = "0.0.0"
description = "exoperimental .."
authors = ["Your Name <you@example.com>"]
license = "LGPL"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
copier = "^9"
jinja2 = "^3"
loguru = "^0.7"
rich = "^13"
typer = "^0.9"
watchgod = "^0.8"
pydantic = "^2"


[tool.poetry.group.dev.dependencies]
doit = "^0.36"
pre-commit = "^3"
mypy = "^1"
ruff = "^0.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
