[tool.poetry]
name = "creat"
version = "0.6.7"
description = "CLI frontend for templating"
authors = ["Your Name <you@example.com>"]
license = "LGPL"
packages = [
    { include = "creat" }
]

[tool.poetry.dependencies]
python = "^3.9"
Jinja2 = "^3.0.3"
loguru = "^0.5.3"
rich = "^10.4.0"
#copier = "^5.1.0"
typer = "^0.4.0"
colorama = "^0.4.4"
#shellingham = "^1.4.0" # does not work on windows
watchgod = "^0.7"
pydantic = "^1.8.2"
typing-extensions = "^4.0.0"
"ruamel.yaml" = "^0.17.16"
multidict = "^5.2.0"

[tool.poetry.dev-dependencies]
pylint = "^2.5.3"
pytest = "^6.2.1"
safety = "^1.10.0"
black = "^21.11b1"
aiohttp = "^3.7.3"
aiohttp_cors = "^0.7.0"
bandit = "^1.7.0"
isort = "^5.8.0"
pre-commit = "^2.9.3"
mypy = "^0.910"
pytest-cov = "^3.0.0"
pytest-timeout = "^2.0.1"
pytest-xprocess = "^0.18.1"
types-Jinja2 = "^2.11.2"

[tool.poetry.scripts]
creat = 'creat.__main__:app'

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

[tool.black]
line-length = 100

[tool.isort]
profile = "black"
multi_line_output = 3

[tool.coverage.run]
branch = true
command_line = '-m pytest'
source = ['creat/']

[tool.coverage.report]
precision = 2
skip_covered = true
fail_under = 90

[tool.pylint.similarities]
min-similarity-lines = 11
ignore-docstrings = true
ignore-comments = true
ignore-imports = true

[tool.pylint.'MESSAGES CONTROL']
max-line-length = 100
disable = [
    "consider-using-f-string",
    "global-statement",
    "import-error",
    "import-outside-toplevel",
    "invalid-name",
    "missing-class-docstring",
    "missing-function-docstring",
    "missing-module-docstring",
    "too-few-public-methods",
    "undefined-loop-variable",
    "protected-access",
    "no-self-use",
    "broad-except",
]
