name: Check creat

on:
  pull_request:
    branches: [ develop ]

jobs:

  check:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ 3.9, 3.10, 3.11 ]

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies with poetry
        run: |
          python -m pip install --upgrade pip
          python -m pip install poetry
          poetry config virtualenvs.create false
          poetry install

      - name: Check code imports style with isort
        run: |
          poetry run isort --check-only --recursive .

      - name: Check code style with black
        run: |
          poetry run black --check .

      - name: Check package vulnerabilities with safety
        run: |
          poetry run safety check

      - name: Check code vulnerabilities with bandit
        run: |
          poetry run bandit -ll -ii -r .

      - name: Check code typing with mypy
        run: |
          poetry run mypy --ignore-missing-imports .

      - name: Check code with pylint
        run: |
          poetry run pylint creat tests

      - name: Test with pytest
        run: |
          poetry run pytest .
