name: Check creat

on:
  pull_request:
    branches: [ develop ]

jobs:

  check:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.10", "3.11", "3.12"]

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies with poetry
        run: |
          python -m pip install --upgrade pip
          python -m pip install poetry
          poetry config virtualenvs.create false
          poetry install

      - name: check with mypy
        run: |
          poetry run mypy creat

      - name: check with ruby
        run: |
          poetry run ruff check creat
